"""메이저 아르카나 타로 카드 도메인 데이터.

프론트엔드의 src/data/tarotCards.ts 와 동기화되어 있습니다.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class TarotCard:
    id: int
    slug: str
    english_name: str
    korean_name: str
    upright_meaning: str
    reversed_meaning: str
    love_meanings: dict[str, str]  # keys: self, other, flow
    tone: str  # positive | neutral | challenging
    keywords: list[str] = field(default_factory=list)


MAJOR_ARCANA: list[TarotCard] = [
    TarotCard(
        id=0,
        slug="the-fool",
        english_name="The Fool",
        korean_name="바보",
        upright_meaning="새로운 시작, 즉흥성, 순수한 끌림",
        reversed_meaning="충동, 미성숙, 방향 상실",
        love_meanings={
            "self": "당신은 아직 이 관계를 정의하기보다 설렘의 가능성을 탐색하고 싶어 합니다.",
            "other": "상대는 분명 호감이 있지만 무게를 싣기보다 가볍게 흐르길 원하는 기색이 있습니다.",
            "flow": "관계는 빠르게 가까워질 수 있지만 기준 없는 속도는 금세 불안으로 번질 수 있습니다.",
        },
        tone="neutral",
        keywords=["fresh", "curious", "risk"],
    ),
    TarotCard(
        id=1,
        slug="the-magician",
        english_name="The Magician",
        korean_name="마법사",
        upright_meaning="의지, 표현력, 끌어당기는 힘",
        reversed_meaning="계산, 과장, 진정성 부족",
        love_meanings={
            "self": "당신은 이 관계를 그냥 두지 않고 직접 움직여 보고 싶은 마음이 강합니다.",
            "other": "상대 역시 당신의 매력을 인식하고 있으며 분명한 반응을 보일 수 있는 상태입니다.",
            "flow": "작은 행동 하나가 관계의 분위기를 바꿀 만큼, 지금은 신호가 잘 먹히는 시기입니다.",
        },
        tone="positive",
        keywords=["spark", "initiative", "chemistry"],
    ),
    TarotCard(
        id=2,
        slug="the-high-priestess",
        english_name="The High Priestess",
        korean_name="여교황",
        upright_meaning="직관, 침묵, 감춰진 진심",
        reversed_meaning="혼란, 비밀, 감정 차단",
        love_meanings={
            "self": "당신은 감정을 쉽게 드러내지 않지만 이미 깊은 직감으로 상대를 읽고 있습니다.",
            "other": "상대는 생각이 많고 감정을 숨기는 편이라 표현보다 침묵으로 마음을 남길 가능성이 큽니다.",
            "flow": "관계는 천천히 깊어질 수 있으나, 분명한 고백보다는 미묘한 분위기와 눈치가 먼저 흐릅니다.",
        },
        tone="neutral",
        keywords=["intuition", "mystery", "silence"],
    ),
    TarotCard(
        id=3,
        slug="the-empress",
        english_name="The Empress",
        korean_name="황후",
        upright_meaning="풍요, 애정 표현, 다정한 안정감",
        reversed_meaning="과잉 기대, 집착, 감정 소진",
        love_meanings={
            "self": "당신은 사랑을 줄 준비가 되어 있고, 관계를 따뜻하게 키우고 싶은 욕구가 분명합니다.",
            "other": "상대는 당신에게 편안함과 매력을 느끼며 더 가까워지고 싶은 마음을 품고 있습니다.",
            "flow": "관계는 정서적 안정과 애정 표현이 쌓일수록 아름답게 자라나는 흐름입니다.",
        },
        tone="positive",
        keywords=["warmth", "abundance", "care"],
    ),
    TarotCard(
        id=4,
        slug="the-emperor",
        english_name="The Emperor",
        korean_name="황제",
        upright_meaning="안정, 기준, 책임감",
        reversed_meaning="통제, 완고함, 거리감",
        love_meanings={
            "self": "당신은 이 관계를 가볍게 소비하기보다 확실한 기준 안에서 보고 싶어 합니다.",
            "other": "상대는 감정이 있어도 쉽게 흔들리지 않으며, 상황을 통제 가능한 범위에서 다루려 합니다.",
            "flow": "관계는 분명한 태도와 책임 있는 행동이 생길 때 비로소 안정적인 진전을 만듭니다.",
        },
        tone="neutral",
        keywords=["structure", "boundaries", "serious"],
    ),
    TarotCard(
        id=5,
        slug="the-hierophant",
        english_name="The Hierophant",
        korean_name="교황",
        upright_meaning="전통, 약속, 공식화",
        reversed_meaning="틀에 갇힘, 관성, 고정관념",
        love_meanings={
            "self": "당신은 감정뿐 아니라 관계의 이름과 방향을 분명히 하고 싶어 합니다.",
            "other": "상대도 가벼운 스쳐 감보다 오래 갈 수 있는 안정된 연결을 의식하고 있습니다.",
            "flow": "관계는 대화와 합의를 통해 자연스럽게 공식적인 형태로 발전할 가능성이 있습니다.",
        },
        tone="positive",
        keywords=["commitment", "trust", "clarity"],
    ),
    TarotCard(
        id=6,
        slug="the-lovers",
        english_name="The Lovers",
        korean_name="연인",
        upright_meaning="상호 끌림, 선택, 진실한 연결",
        reversed_meaning="갈등, 엇갈림, 선택 회피",
        love_meanings={
            "self": "당신의 마음은 이미 강하게 기울어 있으며 이 감정을 진짜 관계로 이어 보고 싶어 합니다.",
            "other": "상대 또한 당신과의 연결을 가볍게 여기지 않고 감정적 선택지로 보고 있습니다.",
            "flow": "관계는 서로의 진심을 확인할수록 급격히 가까워질 수 있는 강한 공명대를 품고 있습니다.",
        },
        tone="positive",
        keywords=["union", "choice", "magnetism"],
    ),
    TarotCard(
        id=7,
        slug="the-chariot",
        english_name="The Chariot",
        korean_name="전차",
        upright_meaning="추진력, 돌파, 의지의 집중",
        reversed_meaning="과속, 충돌, 조급함",
        love_meanings={
            "self": "당신은 더 이상 기다리기보다 지금 상황을 밀고 나가고 싶은 마음이 큽니다.",
            "other": "상대는 감정이 생기면 빠르게 움직일 수 있지만, 동시에 자신의 리듬을 놓치고 싶어 하지는 않습니다.",
            "flow": "관계는 방향만 맞으면 빠르게 진전되지만 서로의 속도가 다르면 긴장도 함께 커집니다.",
        },
        tone="positive",
        keywords=["momentum", "drive", "timing"],
    ),
    TarotCard(
        id=8,
        slug="strength",
        english_name="Strength",
        korean_name="힘",
        upright_meaning="인내, 부드러운 용기, 신뢰",
        reversed_meaning="불안, 자기 의심, 감정 폭발",
        love_meanings={
            "self": "당신은 흔들리는 감정 속에서도 성숙하게 관계를 다루고 싶어 합니다.",
            "other": "상대는 당신에게 안정감을 느끼며 서서히 마음을 열 가능성이 높습니다.",
            "flow": "관계는 강한 자극보다 차분한 신뢰가 쌓일수록 더 단단해지는 흐름입니다.",
        },
        tone="positive",
        keywords=["patience", "trust", "soft-power"],
    ),
    TarotCard(
        id=9,
        slug="the-hermit",
        english_name="The Hermit",
        korean_name="은둔자",
        upright_meaning="거리 두기, 성찰, 조용한 관찰",
        reversed_meaning="고립, 단절, 지나친 회피",
        love_meanings={
            "self": "당신은 감정보다 먼저 스스로의 확신을 찾고 싶어 하며, 쉽게 다가가지 못하고 있습니다.",
            "other": "상대는 마음이 없어서라기보다 지금 자기 안의 생각과 상황에 더 잠겨 있을 수 있습니다.",
            "flow": "관계는 당장 뜨겁게 번지기보다 시간과 여백 속에서 의미를 확인해야 하는 흐름입니다.",
        },
        tone="challenging",
        keywords=["distance", "reflection", "pause"],
    ),
    TarotCard(
        id=10,
        slug="wheel-of-fortune",
        english_name="Wheel of Fortune",
        korean_name="운명의 수레바퀴",
        upright_meaning="전환점, 운의 흐름, 예기치 않은 변화",
        reversed_meaning="반복, 엇박자, 타이밍 손실",
        love_meanings={
            "self": "당신은 이 관계가 우연을 넘어 운명처럼 움직이길 기대하고 있습니다.",
            "other": "상대 역시 당신과의 연결에서 이전과 다른 감정의 변화를 느끼고 있을 수 있습니다.",
            "flow": "관계는 뜻밖의 계기 하나로 분위기가 바뀌며, 타이밍을 잡으면 큰 전환이 가능합니다.",
        },
        tone="positive",
        keywords=["fate", "change", "turning-point"],
    ),
    TarotCard(
        id=11,
        slug="justice",
        english_name="Justice",
        korean_name="정의",
        upright_meaning="균형, 진실, 분명한 판단",
        reversed_meaning="불균형, 회피, 억울함",
        love_meanings={
            "self": "당신은 감정에만 휩쓸리기보다 상황을 냉정하게 보고 싶어 합니다.",
            "other": "상대는 마음이 있어도 쉽게 표현하지 않고, 먼저 관계의 현실성을 재고 있을 수 있습니다.",
            "flow": "관계는 감정보다 사실과 태도의 일관성이 중요하며, 모호함을 정리할수록 선명해집니다.",
        },
        tone="neutral",
        keywords=["truth", "balance", "clarity"],
    ),
    TarotCard(
        id=12,
        slug="the-hanged-man",
        english_name="The Hanged Man",
        korean_name="매달린 사람",
        upright_meaning="멈춤, 관점 전환, 보류",
        reversed_meaning="지연, 정체, 희생의 피로",
        love_meanings={
            "self": "당신은 이 관계를 붙잡고 싶지만 지금은 적극적으로 움직이기보다 상황을 지켜보는 중입니다.",
            "other": "상대는 감정이 없기보다 아직 결정을 미루고 있으며 마음을 정리할 시간이 더 필요합니다.",
            "flow": "관계는 당장 답이 나오기보다 정체된 듯 보이는 시간을 지나며 의미가 드러나는 흐름입니다.",
        },
        tone="challenging",
        keywords=["suspension", "delay", "shift"],
    ),
    TarotCard(
        id=13,
        slug="death",
        english_name="Death",
        korean_name="죽음",
        upright_meaning="끝과 시작, 단절 후 재편, 강한 변화",
        reversed_meaning="미련, 끝맺지 못함, 변화 저항",
        love_meanings={
            "self": "당신은 이전 방식으로는 이 관계가 유지될 수 없다는 사실을 이미 감지하고 있습니다.",
            "other": "상대도 마음의 국면이 바뀌는 중이며, 예전처럼 돌아가기보다 새로운 방식이 필요합니다.",
            "flow": "관계는 큰 전환을 요구하며, 낡은 패턴을 끝내야만 다음 가능성이 열립니다.",
        },
        tone="challenging",
        keywords=["transformation", "release", "ending"],
    ),
    TarotCard(
        id=14,
        slug="temperance",
        english_name="Temperance",
        korean_name="절제",
        upright_meaning="조화, 회복, 균형 잡힌 교류",
        reversed_meaning="엇박자, 감정 과잉, 인내 부족",
        love_meanings={
            "self": "당신은 감정을 급하게 밀어붙이기보다 아름답게 균형을 맞추고 싶어 합니다.",
            "other": "상대는 천천히지만 꾸준하게 마음을 맞춰 갈 수 있는 사람입니다.",
            "flow": "관계는 서두르지 않을수록 오히려 깊어지며, 자연스러운 페이스가 최고의 해답이 됩니다.",
        },
        tone="positive",
        keywords=["healing", "balance", "harmony"],
    ),
    TarotCard(
        id=15,
        slug="the-devil",
        english_name="The Devil",
        korean_name="악마",
        upright_meaning="집착, 강한 유혹, 놓기 어려운 끌림",
        reversed_meaning="해방, 중독 끊기, 패턴 인식",
        love_meanings={
            "self": "당신은 이 관계에 강하게 끌리지만 동시에 감정적으로 묶여 있는 부분도 느끼고 있습니다.",
            "other": "상대 역시 강한 호기심이나 욕망을 느낄 수 있으나 건강한 방식으로 표현하지 못할 수 있습니다.",
            "flow": "관계는 강렬하지만 불균형해지기 쉬워, 서로를 소모시키는 패턴을 경계해야 합니다.",
        },
        tone="challenging",
        keywords=["temptation", "obsession", "intensity"],
    ),
    TarotCard(
        id=16,
        slug="the-tower",
        english_name="The Tower",
        korean_name="탑",
        upright_meaning="급격한 진실, 붕괴, 예기치 않은 충격",
        reversed_meaning="위기 회피, 금 간 구조, 후폭풍",
        love_meanings={
            "self": "당신은 겉으로 버티고 있어도 내면에서는 이 관계의 불안정함을 강하게 느끼고 있습니다.",
            "other": "상대는 감정을 숨기고 있었더라도 갑작스럽게 태도를 바꾸거나 진실을 드러낼 수 있습니다.",
            "flow": "관계는 기존의 애매한 구조가 깨지면서 진짜 본심과 현실을 마주하게 되는 흐름입니다.",
        },
        tone="challenging",
        keywords=["shock", "truth", "breakthrough"],
    ),
    TarotCard(
        id=17,
        slug="the-star",
        english_name="The Star",
        korean_name="별",
        upright_meaning="희망, 치유, 맑은 진심",
        reversed_meaning="불신, 낙담, 기대 저하",
        love_meanings={
            "self": "당신은 여전히 이 관계 안에서 희망과 아름다움을 보고 있습니다.",
            "other": "상대는 당신을 보며 마음이 편안해지고, 감정을 더 건강하게 바라보게 될 수 있습니다.",
            "flow": "관계는 치유와 회복의 결을 타며, 서서히 신뢰를 다시 밝히는 방향으로 움직입니다.",
        },
        tone="positive",
        keywords=["hope", "healing", "gentle"],
    ),
    TarotCard(
        id=18,
        slug="the-moon",
        english_name="The Moon",
        korean_name="달",
        upright_meaning="불확실성, 감정의 파도, 숨은 불안",
        reversed_meaning="혼란 정리, 진실 노출, 두려움 완화",
        love_meanings={
            "self": "당신은 직감적으로 끌리지만 동시에 상대의 진심을 확신하지 못해 흔들리고 있습니다.",
            "other": "상대는 감정이 있어도 혼란과 두려움 때문에 분명한 신호를 주지 못할 수 있습니다.",
            "flow": "관계는 감정의 밀물과 썰물이 커서, 지금은 해석보다 현실 확인이 더 중요합니다.",
        },
        tone="challenging",
        keywords=["uncertainty", "dream", "fear"],
    ),
    TarotCard(
        id=19,
        slug="the-sun",
        english_name="The Sun",
        korean_name="태양",
        upright_meaning="기쁨, 선명함, 드러나는 호감",
        reversed_meaning="과열, 자의식, 기대 과다",
        love_meanings={
            "self": "당신의 마음은 매우 솔직하고, 사랑을 숨기기보다 밝게 표현하고 싶어 합니다.",
            "other": "상대는 당신과 있을 때 감정이 맑아지고 즐거움을 분명하게 느낄 가능성이 큽니다.",
            "flow": "관계는 오해보다 확신이 커지며, 자연스럽고 건강한 방식으로 가까워질 수 있습니다.",
        },
        tone="positive",
        keywords=["joy", "clarity", "warmth"],
    ),
    TarotCard(
        id=20,
        slug="judgement",
        english_name="Judgement",
        korean_name="심판",
        upright_meaning="각성, 재평가, 다시 부름",
        reversed_meaning="미련, 후회, 과거 회피",
        love_meanings={
            "self": "당신은 이 관계를 통해 자신의 진짜 감정과 원하는 사랑의 형태를 다시 깨닫고 있습니다.",
            "other": "상대 역시 지나간 감정이나 선택을 다시 돌아보며 새로운 판단을 내릴 수 있습니다.",
            "flow": "관계는 과거의 패턴을 재정리한 뒤, 다시 연결되거나 전혀 다른 결론으로 나아갈 수 있습니다.",
        },
        tone="positive",
        keywords=["awakening", "return", "reckoning"],
    ),
    TarotCard(
        id=21,
        slug="the-world",
        english_name="The World",
        korean_name="세계",
        upright_meaning="완성, 성숙한 결실, 조화로운 마무리",
        reversed_meaning="미완성, 마지막 한 걸음 부족, 반복",
        love_meanings={
            "self": "당신은 단순한 설렘보다 완성도 있는 관계를 원하며, 이제 그 기준이 분명해졌습니다.",
            "other": "상대는 당신과의 관계에서 안정감과 장기적인 가능성을 동시에 볼 수 있습니다.",
            "flow": "관계는 자연스럽게 다음 단계로 이어지며, 서로에게 맞는 리듬을 찾을 가능성이 높습니다.",
        },
        tone="positive",
        keywords=["completion", "maturity", "fulfillment"],
    ),
]
